# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Chrome Extension upload & publish
    - uses: Passiverecords/chrome-extension-upload-action@1.4.1
      with:
        refresh-token:  ${{ secrets.GOOG_REFRESH_TOKEN }}
        client-id:  ${{ secrets.GOOG_CLIENT_ID }}
        client-secret:  ${{ secrets.GOOD_CLIENT_SECRET }}
        file-name: './dist/chrome-dist.zip'
        app-id: 'cckhnpaedijpapngkpjodffjfiemhlnf'
        publish: True
